# persistent-volume-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-pvc
  namespace: cicd-tekton
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
