apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-binding
  namespace: cicd-tekton
subjects:
- kind: ServiceAccount
  name: default
  namespace: cicd-tekton
roleRef:
  kind: Role
  name: deployer
  apiGroup: rbac.authorization.k8s.io

